# Use Ctrl-S for commands
unbind C-b
set -g prefix C-s

set-window-option -g mode-keys vi
set-window-option -g automatic-rename on
# Set colors
set-option -g default-terminal "screen-256color"

set-option -g display-panes-time 3000

# important to prevent delay switching mode in vim
set -s escape-time 0

# Set reload key to r
bind r source-file ~/.tmux.conf

set -g set-titles on
# set -g set-titles-string '#(whoami) :: #h'

# Remap window navigation to vim
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key j
bind-key j select-pane -D
unbind-key l
bind-key l select-pane -R

# Colemak style
unbind-key e
bind-key e select-pane -D
unbind-key u
bind-key u select-pane -U
unbind-key n
bind-key n select-pane -L
unbind-key i
bind-key i select-pane -R

# Set status bar (I turned it off since I don't use tmux enough to need
# a status bar)
set -g status off
# set -g status-utf8 on
# set -g status-bg black
# set -g status-fg white
# set -g status-interval 5
# set -g status-left-length 90
# set -g status-right-length 60
# set -g status-left "#[fg=Green]#(whoami)#[fg=white]::#[fg=blue]#(hostname -s)#[fg=white]::"
# set -g status-justify left
# set -g status-right '#[fg=Cyan]#S #[fg=white]%a %d %b %R'

# Turn mouse mode on by default, and add 2 bindings to toggle it
set -g mouse on
bind m set -g mouse on \; display "MOUSE ON"
bind M set -g mouse off \; display "MOUSE OFF"
#set -ga terminal-overrides ':Ss=\eE[%p1%d q:Se=\eE[2 q'
#set -ga terminal-overrides ':Ss=\eE[2 q:Se=\eE[6 q'
