# Use Ctrl-S for commands
unbind C-b
set -g prefix C-s

set-window-option -g mode-keys vi
set-window-option -g automatic-rename on
# Set colors
set-option -g default-terminal "screen-256color"

set-option -g display-panes-time 3000

# important to prevent delay switching mode in vim
set -s escape-time 0

# Set reload key to r
bind r source-file ~/.tmux.conf

set -g set-titles on
# set -g set-titles-string '#(whoami) :: #h'

# Remap window navigation to vim
# (not using right now... I usually just do the i3 windows)
# unbind-key k
# bind-key k select-pane -U
# unbind-key h
# bind-key h select-pane -L
# unbind-key j
# bind-key j select-pane -D
# unbind-key l
# bind-key l select-pane -R

# # Colemak style
# unbind-key e
# bind-key e select-pane -D
# unbind-key u
# bind-key u select-pane -U
# unbind-key n
# bind-key n select-pane -L
# unbind-key i
# bind-key i select-pane -R

# Window switching (copy from Odoo keybinding)
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-1 select-window -t 0
bind -n M-2 select-window -t 1
bind -n M-3 select-window -t 2
bind -n M-4 select-window -t 3
bind -n M-5 select-window -t 4
bind -n M-6 select-window -t 5
bind -n M-7 select-window -t 6
bind -n M-8 select-window -t 7
bind -n M-9 select-window -t 8

# Set status bar (I turned it off since I don't use tmux enough to need
# a status bar)
# set -g status off
set -g status on
set -g status-bg black
set -g status-fg white
set -g status-interval 5
set -g status-left-length 90
set -g status-right-length 60
set -g status-left "#[fg=Green]#(whoami)#[fg=white]::#[fg=blue]#(hostname -s)#[fg=white]::"
set -g status-justify left
set -g status-right '#[fg=Cyan]#S #[fg=white]%a %d %b %R'

# Turn mouse mode on by default, and add 2 bindings to toggle it
set -g mouse on
bind m set -g mouse on \; display "MOUSE ON"
bind M set -g mouse off \; display "MOUSE OFF"
#set -ga terminal-overrides ':Ss=\eE[%p1%d q:Se=\eE[2 q'
#set -ga terminal-overrides ':Ss=\eE[2 q:Se=\eE[6 q'
