#!/bin/sh
# vim: ft=sh
#
# Wrapper to invoke rofi with a list of hosts and call xfreerdp.
# The hosts are stored in ~/.rdp-hosts, in a format:

# Name : Address : User : Domain : Password
# TODO we should read the remmina files and use remmina instead of xfreerdp, maybe?

get_rdp_hosts() {
    #grep -v '^#' ~/.rdp-hosts | cut -d ':' -f 1
    grep '^name=' ~/.remmina/*.remmina | cut -d '=' -f 2 | sort
}

run_remmina() {
    file=$(grep -l "^name=$1" ~/.remmina/*.remmina)
    [[ -z "$file" ]] && exit 1
    remmina -c $file
}

run_freerdp() {
    line=$(grep "^$1:" ~/.rdp-hosts | tr -d ' ')
    if [[ -z "$line" ]]
    then
        exit 1
    fi
    IFS=: read name address username domain password port <<< "$line"

    [[ -n "$port" ]] && address="$address:$port"

    # Disabling glyph-cache improves performance in scrolling terminal windows
    if ! xfreerdp -grab-keyboard /bpp:16 +compression /network:broadband-low /jpeg-quality:60 -glyph-cache /p:"$password" /d:$domain /u:$username /v:$address /f +clipboard /cert-ignore > /tmp/xfreerdp.log 2>&1
    then
        msg=$(grep ERROR /tmp/xfreerdp.log | cut -d- -f2-)
        notify-send -u critical "Connection Failed" "$msg"
    else
        rm /tmp/xfreerdp.log
    fi
    #awk -F: '{system("xfreerdp -grab-keyboard /p:"$5" /d:"$4" /u:"$3" /v:"$2" /f +clipboard /cert-ignore")}') || notify-send -u critical "Connection Failed"
}

RDP_HOST=$( (get_rdp_hosts) | rofi -dmenu -i -p "Select RDP:")

if [[ ! -z "$RDP_HOST" ]]
then
#    get_rdp_params "$RDP_HOST"
    run_remmina $RDP_HOST
fi
