#!/bin/sh

# IP=`dig @ns1.google.com -t txt o-o.myaddr.l.google.com +short 2>/dev/null`
IP=`dig whoami.akamai.net. @ns1-1.akamaitech.net. +short 2>/dev/null`
# IP=`curl ifconfig.co 2>/dev/null`
# IP=`curl v4.ifconfig.co 2>/dev/null`
if (( $? > 0 )); then
    echo "DOWN"
    echo "DOWN"
    echo "#ff0000"
else
    IP=`echo $IP | tr -d '"'`
    #echo "{\"full_text\": \"$IP\", \"color\": \"#859900\"}"
    echo $IP
    if [ "$BLOCK_BUTTON" = "3" ]; then
        echo -n $IP | xclip
    fi
fi
