#!/bin/sh

sleep 2


# exec --no-startup-id i3-msg 'workspace 5: ILX; exec chromium --profile-directory=Profile\\ 3'
# exec --no-startup-id i3-msg 'workspace $workspace3, exec remmina, workspace $workspace1'
#exec --no-startup-id "i3-msg 'workspace $workspace9; append_layout ~/.config/i3/layouts/messenger-layout.json'"
# exec audacious
# try DB instead of Auda for a bit
# deadbeef &
# connect display link output
(xrandr --listproviders | grep -q "modesetting") && xrandr --setprovideroutputsource 1 0
spotify &
skype &
workrave &
# Compton provides transparency (which we only use for Rofi)
compton -b
# Allow tapping win key for escape
# (tried with caps but it was generally annoying)
# Not too sure about the Shift one but left shift was getting
# hit too much by mistake
xcape -e "Alt_L=BackSpace;Super_R=Return" -t 350
