[media]
command=/usr/lib/i3blocks/mediaplayer
instance=audacious
interval=5
signal=10
label=
color=#d33682
separator=false

[volume]
label=
command=/usr/lib/i3blocks/volume
#color=#a8eb3c
color=#Ea83B6
interval=once
signal=10

[memory]
label=
command=/usr/lib/i3blocks/memory
separator=false
interval=30
color=#009900

[load_average]
command=~/.config/i3/blocks/load_average
color=#009900
interval=10

[bandwidth]
label=
color=#859900
command=/usr/lib/i3blocks/bandwidth
interval=5



[date]
command=~/.config/i3/blocks/calendar
interval=15
label=
color=#dddddd
