command=~/.config/i3/blocks/$BLOCK_NAME
interval=10

[volume]
label=
command=/usr/lib/i3blocks/volume
#color=#a8eb3c
color=#Ea83B6
interval=once
signal=10
separator=false

[deadbeef]
color=#Ea83B6
# instance=audacious
# interval=once
# signal=10
# color=#d33682

[memory]
label=
separator=false
interval=15
color=#009900

[load_average]
color=#009900
interval=10

[bandwidth]
label=
color=#859900
command=/usr/lib/i3blocks/bandwidth
#separator=false

[iface]
label=L:
color=#859900

[public_ip]
label=W:
#format=json
interval=30
color=#859900

[calendar]
interval=15
label=
color=#dddddd
