[media]
command=/usr/lib/i3blocks/mediaplayer
instance=audacious
interval=5
signal=10
label=
color=#d33682

[memory]
label=
command=/usr/lib/i3blocks/memory
separator=false
interval=30
color=#009900

[load_average]
command=~/.config/i3/blocks/load_average
color=#009900
interval=10

[bandwidth]
label=
color=#859900
command=/usr/lib/i3blocks/bandwidth
interval=5


#[volume]
#label=V
#command=/usr/lib/i3blocks/volume
#color=#d33682
#interval=once
#signal=12

[date]
command=~/.config/i3/blocks/calendar
interval=15
label=
color=#dddddd
