UseCanonicalName Off

<VirtualHost *:80>
	ServerAlias *.wink.dev
  VirtualDocumentRoot /home/nico/www/wink/web
</VirtualHost>

<VirtualHost *:80>
  ServerAlias *.dev
  VirtualDocumentRoot /home/nico/www/%1/web
</VirtualHost>

<VirtualHost *:80>
	ServerAlias	*.wink
	VirtualDocumentRoot /home/nico/www/wink/web
</VirtualHost>

<Directory /home/nico/www>
  # Order allow,deny
  # Allow from all
  Require all granted
  AllowOverride All
</Directory>

